logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic
  ports:
  - "5555:5555"

mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
  - "27017:27017"

redis:
  extends:
    file: common.yml
    service: redis
  ports:
  - "6379:6379"

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
  ports:
  - "5601:5601"

elastic:
  extends:
    file: common.yml
    service: elastic
  ports:
  - "9200:9200"

postfix:
  extends:
    file: common.yml
    service: postfix
  ports:
  - "25:25"

backend:
  extends:
    file: common.yml
    service: backend
  environment:
   - SUPERDESK_RELOAD=True
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_CLIENT_URL=http://localhost:9000
  volumes:
   - ../server:/opt/superdesk/
   - ./Procfile:/opt/superdesk/Procfile
  ports:
   - "5000:5000"
   - "5050:5050"
   - "5100:5100"

frontend:
  extends:
    file: common.yml
    service: frontend
  command: sh -c "npm install -g grunt-cli ; grunt --force server --server='http://localhost:5000/api' --ws='ws://localhost:5100'"
  volumes:
   - ../client:/opt/superdesk-client/
  ports:
   - "9000:9000"
   - "35729:35729"
